## Assignment No. 1

# Create a numpy array and do 20 nupy operation on it

In [1]:
import numpy as np

In [4]:
 arr = np.arange(1,11)

In [5]:
arr.mean()

5.5

In [10]:
np.median(arr)

5.5

In [12]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [13]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [14]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [16]:
np.arctan(arr)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077,
       1.40564765, 1.42889927, 1.44644133, 1.46013911, 1.47112767])

In [21]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [20]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [22]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [23]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [24]:
arr**10

array([         1,       1024,      59049,    1048576,    9765625,
         60466176,  282475249, 1073741824, -808182895, 1410065408],
      dtype=int32)

In [25]:
arr * 54

array([ 54, 108, 162, 216, 270, 324, 378, 432, 486, 540])

In [26]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [27]:
2*(arr)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr==2

array([False,  True, False, False, False, False, False, False, False,
       False])

In [29]:
arr==3

array([False, False,  True, False, False, False, False, False, False,
       False])

In [30]:
arr==5

array([False, False, False, False,  True, False, False, False, False,
       False])

In [32]:
arr_copy = arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr_copy + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
arr_copy * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [35]:
arr_copy / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
arr_copy**arr

array([         1,          4,         27,        256,       3125,
            46656,     823543,   16777216,  387420489, 1410065408],
      dtype=int32)

## Assignment 3

# Assignment from periandata data file/Exercise

In [37]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
np.ones((10,10))*5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [42]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [48]:
np.arange(0, 51, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [49]:
my_matrix = [[0,1,2], [3,4,5],[6,7,8]]
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.random.randn(26)

array([ 0.89239146,  0.7390736 , -0.51403213,  0.79512822,  0.35457365,
        0.96233391, -1.73479365, -0.43782754,  0.51558715,  0.67285179,
        1.50807267,  2.00341921,  0.74165851,  0.49715306,  0.28139574,
       -0.17814865,  0.76899193,  0.14159672,  0.56628307,  0.25128847,
        0.39128951,  0.40463889, -1.74174258,  0.4038857 ,  1.40065032,
        0.92102878])

In [61]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [62]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [63]:
matrix = [[ 1,  2,  3,  4,  5], [ 6,  7,  8,  9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]
np.array(matrix)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
mat = [[12, 13, 14, 15], [17, 18, 19, 20], [22, 23, 24, 25]]
np.array(mat)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [69]:
matrix[4]

[21, 22, 23, 24, 25]

In [67]:
matrix[3:]

[[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]

In [70]:
np.sum(matrix)

325

In [72]:
np.std(matrix)

7.211102550927978

In [73]:
np.sum(matrix, axis=1)

array([ 15,  40,  65,  90, 115])

## Thank You for the Assignment

# Good Day, Have a Nice day!