In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.random.rand(2)

array([0.19777478, 0.13385003])

In [17]:
np.random.randn(2)

array([ 0.59172787, -1.01088498])

In [20]:
np.random.randint(1,100,10)

array([96, 92, 68, 35, 78, 46, 15, 24, 12, 10])

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr
arr.shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.shape
ranarr.reshape(2,5)

array([[ 5, 46, 42, 10, 49],
       [33,  1, 33, 15, 35]])

In [31]:
ranarr.max()

49

In [34]:
ranarr.argmax()

4

In [35]:
ranarr.argmin()

6

In [36]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [39]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [40]:
arr.dtype

dtype('int32')

In [41]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
# create sample array
arr = np.arange(0,11)

# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Get a value at an index
arr[8]

8

In [57]:
# Get values in a range
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
# Reset array we'll see why I had to reset in a moment
arr = np.arange(0,11)


#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# Important notes on slices
slice_of_arr = arr[0:6]

# show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [64]:
# Change Slice
slice_of_arr[:] = 99

#show slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
# To get a copy need to be explicit
arr_copy = arr.copy()

# show arr_copy
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
# 2d array SHOW
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))

#show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [69]:
# Formatt is arr_2d[row][col] or arr_2d[row,col]

#Getting individual element value
arr_2d[1,0]

20

In [83]:
# 2D array slicing

#shape(2,2) from right corner
arr_2d[:2,1:]

array([[0, 0],
       [1, 1]])

In [87]:
arr2d = np.zeros((10,10))
arr_length = len(arr) 

In [90]:
#set up for array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [91]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [94]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [96]:
bool_arr = arr >4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [97]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [102]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [103]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
# Warning on division by zero, but not error!
# Just replaced with them
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [106]:
# Also warning, but not an error instead infinity
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [107]:
# Calculating exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [108]:
np.max(arr)

9

In [109]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [110]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])